# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'TEST-Sub-ljankow-01 (fbdcee66-8eff-4939-9425-b08f43e87665)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ARM_new_Group-01'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    deploymentMode: 'Incremental'